version: '3.8'

services:
  web:
    container_name: app
    image: ${BASE_IMAGE_TAG:-lawyer_image}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: /bin/bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done; 
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input &&
      gunicorn core.wsgi:application -b 0.0.0.0:8000 --reload -w 4 --timeout 120
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/mediafiles
    restart: always

  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: