# Generated by Django 4.2.4 on 2023-08-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания заявки"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя клиента")),
                (
                    "email",
                    models.CharField(max_length=40, verbose_name="Почта клиента"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, verbose_name="Номер телефона клиента"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата встречи")),
                ("comment", models.TextField(verbose_name="Комментарий от клиента")),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="ContactNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "whatsapp",
                    models.BooleanField(default=False, verbose_name="Whatsapp"),
                ),
            ],
            options={
                "verbose_name": "Номер телефона",
                "verbose_name_plural": "Номера телефона",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Язык")),
            ],
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=40, verbose_name="Почта")),
                ("address", models.CharField(max_length=150, verbose_name="Адрес")),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lawyer.language",
                        verbose_name="Язык информации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактные информации",
            },
        ),
    ]
